; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.12"

; Profiles
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[standard][download][type] = ""
projects[standard][download][url] = ""
projects[standard][type] = "profile"

; Modules
projects[views_bulk_operations][subdir] = "sites/all/modules/contrib/views_bulk_operations"
projects[views_bulk_operations][version] = "3.0-rc1"

projects[admin_menu][subdir] = "sites/all/modules/contrib/admin_menu"
projects[admin_menu][version] = "3.0-rc1"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[audiofield][download][type] = ""
projects[audiofield][download][url] = ""
projects[audiofield][type] = "module"
projects[audiofield][subdir] = "sites/all/modules/contrib/audiofield"
projects[audiofield][version] = "1.0-beta3"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[beast][download][type] = ""
projects[beast][download][url] = ""
projects[beast][type] = "module"
projects[beast][subdir] = "sites/all/modules/custom/beast"
projects[beast][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[better_formats][download][type] = ""
projects[better_formats][download][url] = ""
projects[better_formats][type] = "module"
projects[better_formats][subdir] = "sites/all/modules/contrib/better_formats"
projects[better_formats][version] = "1.x-dev"

projects[ctools][subdir] = "sites/all/modules/contrib/ctools"
projects[ctools][version] = "1.0-rc1"

projects[chart][subdir] = "sites/all/modules/contrib/chart"
projects[chart][version] = "1.1"

projects[collapsiblock][subdir] = "sites/all/modules/contrib/collapsiblock"
projects[collapsiblock][version] = "1.0"

projects[css_injector][subdir] = "sites/all/modules/contrib/css_injector"
projects[css_injector][version] = "1.7"

projects[devel][subdir] = "sites/all/modules/contrib/devel"
projects[devel][version] = "1.2"

projects[disqus][subdir] = "sites/all/modules/contrib/disqus"
projects[disqus][version] = "1.9"

projects[entity][subdir] = "sites/all/modules/contrib/entity"
projects[entity][version] = "1.0-rc1"

projects[features][subdir] = "sites/all/modules/contrib/features"
projects[features][version] = "1.0-beta6"

projects[field_group][subdir] = "sites/all/modules/contrib/field_group"
projects[field_group][version] = "1.1"

projects[field_redirection][subdir] = "sites/all/modules/contrib/field_redirection"
projects[field_redirection][version] = "1.0"

projects[fieldset_helper][subdir] = "sites/all/modules/contrib/fieldset_helper"
projects[fieldset_helper][version] = "2.x-dev"

projects[filefield_sources][subdir] = "sites/all/modules/contrib/filefield_sources"
projects[filefield_sources][version] = "1.4"

projects[fivestar][subdir] = "sites/all/modules/contrib/fivestar"
projects[fivestar][version] = "2.x-dev"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[getid3][download][type] = ""
libraries[getid3][download][url] = ""
libraries[getid3][directory_name] = "getid3"
libraries[getid3][type] = "library"

; Modules
projects[globalredirect][subdir] = "sites/all/modules/contrib/globalredirect"
projects[globalredirect][version] = "1.3"

projects[google_analytics_reports][subdir] = "sites/all/modules/contrib/google_analytics_reports"
projects[google_analytics_reports][version] = "1.0"

projects[google_analytics][subdir] = "sites/all/modules/contrib/google_analytics"
projects[google_analytics][version] = "1.2"

projects[imageapi_optimize][subdir] = "sites/all/modules/contrib/imageapi_optimize"
projects[imageapi_optimize][version] = "1.x-dev"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[imagecache_actions][download][type] = ""
projects[imagecache_actions][download][url] = ""
projects[imagecache_actions][type] = "module"
projects[imagecache_actions][subdir] = "sites/all/modules/contrib/imagecache_actions"
projects[imagecache_actions][version] = "0.0"

projects[imagecache_profiles][subdir] = "sites/all/modules/contrib/imagecache_profiles"
projects[imagecache_profiles][version] = "1.0-rc2"

projects[insert][subdir] = "sites/all/modules/contrib/insert"
projects[insert][version] = "1.1"

projects[jcarousel][subdir] = "sites/all/modules/contrib/jcarousel"
projects[jcarousel][version] = "2.4-alpha3"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[job_scheduler][download][type] = ""
projects[job_scheduler][download][url] = ""
projects[job_scheduler][type] = "module"
projects[job_scheduler][subdir] = "sites/all/modules/contrib/job_scheduler"
projects[job_scheduler][version] = "2.0-alpha2"

projects[libraries][subdir] = "sites/all/modules/contrib/libraries"
projects[libraries][version] = "1.0"

projects[link][subdir] = "sites/all/modules/contrib/link"
projects[link][version] = "1.0-alpha3"

projects[logintoboggan][subdir] = "sites/all/modules/contrib/logintoboggan"
projects[logintoboggan][version] = "1.2"

projects[mailchimp][subdir] = "sites/all/modules/contrib/mailchimp"
projects[mailchimp][version] = "2.0"

projects[mailsystem][subdir] = "sites/all/modules/contrib/mailsystem"
projects[mailsystem][version] = "2.28"

projects[markdown][subdir] = "sites/all/modules/contrib/markdown"
projects[markdown][version] = "1.0"

projects[masquerade][subdir] = "sites/all/modules/contrib/masquerade"
projects[masquerade][version] = "1.0-rc3"

projects[metatag][subdir] = "sites/all/modules/contrib/metatag"
projects[metatag][version] = "1.0-alpha3"

projects[mimemail][subdir] = "sites/all/modules/contrib/mimemail"
projects[mimemail][version] = "1.0-alpha1+4-dev"

projects[references][subdir] = "sites/all/modules/contrib/references"
projects[references][version] = "2.0"

projects[oauth][subdir] = "sites/all/modules/contrib/oauth"
projects[oauth][version] = "3.0"

projects[pathauto][subdir] = "sites/all/modules/contrib/pathauto"
projects[pathauto][version] = "1.0"

projects[pathologic][subdir] = "sites/all/modules/contrib/pathologic"
projects[pathologic][version] = "1.4"

projects[profiler_builder][subdir] = "sites/all/modules/contrib/profiler_builder"
projects[profiler_builder][version] = "1.0-alpha2"

projects[realname][subdir] = "sites/all/modules/contrib/realname"
projects[realname][version] = "1.0-rc2"

projects[shorten][subdir] = "sites/all/modules/contrib/shorten"
projects[shorten][version] = "1.1"

projects[redirect][subdir] = "sites/all/modules/contrib/redirect"
projects[redirect][version] = "1.0-beta4"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[simpleping][download][type] = ""
projects[simpleping][download][url] = ""
projects[simpleping][type] = "module"
projects[simpleping][subdir] = "sites/all/modules/contrib/simpleping"
projects[simpleping][version] = "1.05"

projects[themekey][subdir] = "sites/all/modules/contrib/themekey"
projects[themekey][version] = "1.5"

projects[token][subdir] = "sites/all/modules/contrib/token"
projects[token][version] = "1.0-rc1"

projects[view_unpublished][subdir] = "sites/all/modules/contrib/view_unpublished"
projects[view_unpublished][version] = "1.0"

projects[views][subdir] = "sites/all/modules/contrib/views"
projects[views][version] = "3.1"

projects[views_data_export][subdir] = "sites/all/modules/contrib/views_data_export"
projects[views_data_export][version] = "3.0-beta5"

projects[views_php][subdir] = "sites/all/modules/contrib/views_php"
projects[views_php][version] = "1.x-dev"

projects[votingapi][subdir] = "sites/all/modules/contrib/votingapi"
projects[votingapi][version] = "2.4"

projects[xmlsitemap][subdir] = "sites/all/modules/contrib/xmlsitemap"
projects[xmlsitemap][version] = "2.0-beta3"

; Themes
projects[acquia_marina][version] = "1.x-dev"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[acquia_prosper][download][type] = ""
projects[acquia_prosper][download][url] = ""
projects[acquia_prosper][type] = "theme"
projects[acquia_prosper][version] = "1.x-dev"

projects[adaptivetheme][version] = "2.1"

projects[omega][subdir] = "sites/all/themes"
projects[omega][version] = "3.0"

projects[analytic][version] = "1.x-dev"

projects[bluemasters][version] = "1.2"

projects[fusion][version] = "1.0-alpha1"

projects[marinelli][version] = "3.0-beta11"

projects[mix_and_match][version] = "1.x-dev"

projects[pixture_reloaded][version] = "2.2"

projects[sky][version] = "1.6"

projects[tarski][version] = "1.8"

projects[zen][version] = "3.1"

; Modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[adserve][download][type] = ""
projects[adserve][download][url] = ""
projects[adserve][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[blink][download][type] = ""
projects[blink][download][url] = ""
projects[blink][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[blink_externalize][download][type] = ""
projects[blink_externalize][download][url] = ""
projects[blink_externalize][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[crossdog][download][type] = ""
projects[crossdog][download][url] = ""
projects[crossdog][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[image_scale9actions][download][type] = ""
projects[image_scale9actions][download][url] = ""
projects[image_scale9actions][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[koc][download][type] = ""
projects[koc][download][url] = ""
projects[koc][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[kwgoals][download][type] = ""
projects[kwgoals][download][url] = ""
projects[kwgoals][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[linklist_maintainer][download][type] = ""
projects[linklist_maintainer][download][url] = ""
projects[linklist_maintainer][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[rss_permissions][download][type] = ""
projects[rss_permissions][download][url] = ""
projects[rss_permissions][type] = "module"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[player][download][type] = ""
libraries[player][download][url] = ""
libraries[player][directory_name] = "player"
libraries[player][type] = "library"

