<?php
/**
 * Implement hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
 
 
/*
 Ok, what do we have to set?
 
 
*/ 
function beast_profile_install() {
  variable_set('getid3_path', 'profiles/beast/libraries/getid3/getid3');
   
   
  include_once DRUPAL_ROOT . '/profiles/minimal/minimal.install';
  minimal_install();
}

function beast_install() {
   beast_profile_install();
}



